[package]
name = "mmorpg_server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
spacetimedb = "1.3.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "2", optional = true }

[features]
nlp_webhook = ["ureq"]
